# Generated by Django 3.2.5 on 2021-07-11 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_bidentificador', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20, null=True)),
                ('catalogo', models.CharField(max_length=20, null=True)),
                ('EntradaNoCatalogo', models.DateField(auto_now_add=True)),
                ('Lingua', models.CharField(max_length=20, null=True)),
                ('Descrisao', models.CharField(max_length=20, null=True)),
                ('palavrachave', models.CharField(max_length=20, null=True)),
                ('Corbertura', models.CharField(max_length=20, null=True)),
                ('Estrtura', models.CharField(max_length=20, null=True)),
                ('NiveldeAgregacao', models.IntegerField(default=0)),
                ('Versao', models.CharField(max_length=20, null=True)),
                ('Status', models.CharField(max_length=10, null=True)),
                ('ContribuinteFuncao', models.CharField(max_length=20, null=True)),
                ('ContribuinteEntidadae', models.CharField(max_length=20, null=True)),
                ('ContribuinteData', models.CharField(max_length=20, null=True)),
                ('identificador', models.CharField(max_length=20, null=True)),
                ('catalogoMeta', models.CharField(max_length=20, null=True)),
                ('catalogoMetaEntrada', models.CharField(max_length=20, null=True)),
                ('catalogoMetaData', models.CharField(max_length=20, null=True)),
                ('EsquemaMeta', models.CharField(max_length=20, null=True)),
                ('idiomameta', models.CharField(max_length=20, null=True)),
                ('formato', models.CharField(max_length=20, null=True)),
                ('tamanho', models.CharField(max_length=20, null=True)),
                ('localizacao', models.CharField(max_length=20, null=True)),
                ('requisitoTipo', models.CharField(max_length=20, null=True)),
                ('requisitoNome', models.CharField(max_length=20, null=True)),
                ('Observacao', models.CharField(max_length=20, null=True)),
                ('outrosRequitos', models.CharField(max_length=20, null=True)),
                ('duracao', models.CharField(max_length=20, null=True)),
                ('tipodeinteratividade', models.CharField(max_length=20, null=True)),
                ('tipodeRecursodeAprendizagem', models.CharField(max_length=20, null=True)),
                ('niveldeinteratividade', models.CharField(max_length=20, null=True)),
                ('densidadesemantica', models.CharField(max_length=20, null=True)),
                ('funcaodousuariofinalpretendido', models.CharField(max_length=20, null=True)),
                ('contexto', models.CharField(max_length=20, null=True)),
                ('faixaEtaria', models.CharField(max_length=20, null=True)),
                ('dificuldade', models.CharField(max_length=20, null=True)),
                ('TempodeAprendizagem', models.CharField(max_length=20, null=True)),
                ('DescrisaoEducacional', models.CharField(max_length=20, null=True)),
                ('idioma', models.CharField(max_length=20, null=True)),
                ('custo', models.CharField(max_length=20, null=True)),
                ('DireitosautoraisRestricoes', models.CharField(max_length=20, null=True)),
                ('DescrisaoDireitos', models.CharField(max_length=20, null=True)),
                ('tipoRelacao', models.CharField(max_length=20, null=True)),
                ('recursoRelacao', models.CharField(max_length=20, null=True)),
                ('pessoaAnotacao', models.CharField(max_length=20, null=True)),
                ('dataanotacao', models.CharField(max_length=20, null=True)),
                ('descrisaoanotacao', models.CharField(max_length=20, null=True)),
                ('closificacaoObjetivo', models.CharField(max_length=20, null=True)),
                ('taxon', models.CharField(max_length=20, null=True)),
                ('taxonFonte', models.CharField(max_length=20, null=True)),
                ('taxonId', models.CharField(max_length=20, null=True)),
                ('taxonEntrada', models.CharField(max_length=20, null=True)),
                ('classificacaoDescrisao', models.CharField(max_length=20, null=True)),
                ('PalavraPasseClassificacao', models.CharField(max_length=20, null=True)),
                ('autor', models.CharField(max_length=20, null=True)),
                ('ano_pulicacao', models.IntegerField(default=2020)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('Npaginas', models.IntegerField(default=0)),
                ('editora', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
