# Generated by Django 3.2.5 on 2021-07-11 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_book', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_pulicacao', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('Npaginas', models.IntegerField()),
                ('editora', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
