# Generated by Django 3.2.5 on 2021-07-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='pages',
            new_name='Npaginas',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='relese_year',
            new_name='ano_pulicacao',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='create_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='publish_company',
            new_name='editora',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='title',
            new_name='titulo',
        ),
    ]
