# Generated by Django 3.2.4 on 2021-07-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='criado_em',
            new_name='EntradaNoCatalogo',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='id_book',
            new_name='id_bidentificador',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='ContribuinteData',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='ContribuinteEntidadae',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='ContribuinteFuncao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Corbertura',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Descrisao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='DescrisaoDireitos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='DescrisaoEducacional',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='DireitosautoraisRestricoes',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='EsquemaMeta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Estrtura',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Lingua',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='NiveldeAgregacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Observacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='PalavraPasseClassificacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='TempodeAprendizagem',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Versao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='catalogo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='catalogoMeta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='catalogoMetaData',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='catalogoMetaEntrada',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='classificacaoDescrisao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='closificacaoObjetivo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='contexto',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='custo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='dataanotacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='densidadesemantica',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='descrisaoanotacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='dificuldade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='duracao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='faixaEtaria',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='formato',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='funcaodousuariofinalpretendido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='identificador',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='idioma',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='idiomameta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='localizacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='niveldeinteratividade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='outrosRequitos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='palavrachave',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='pessoaAnotacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='recursoRelacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='requisitoNome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='requisitoTipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tamanho',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='taxon',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='taxonEntrada',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='taxonFonte',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='taxonId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipoRelacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipodeRecursodeAprendizagem',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipodeinteratividade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='Npaginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='ano_pulicacao',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='autor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='editora',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='titulo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
