# Generated by Django 3.2.5 on 2021-08-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210809_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='id_bidentificador',
            new_name='id_identificador',
        ),
    ]
