# Generated by Django 3.2.5 on 2021-09-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alterar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cadastrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='excluir',
            field=models.BooleanField(default=False),
        ),
    ]
